-- schema.sql (SQL Server)
IF OBJECT_ID('INGREDIENTS','U') IS NOT NULL DROP TABLE INGREDIENTS;
IF OBJECT_ID('INSTRUCTIONS','U') IS NOT NULL DROP TABLE INSTRUCTIONS;
IF OBJECT_ID('RECIPES','U')     IS NOT NULL DROP TABLE RECIPES;
GO

CREATE TABLE RECIPES (
  RecipeID INT NOT NULL IDENTITY(101,1) PRIMARY KEY,
  Name VARCHAR(100) NOT NULL UNIQUE,
  Cuisine_Type VARCHAR(100) NULL,
  Cooking_Time INT NOT NULL,
  Difficulty_Level INT NOT NULL
);
GO

CREATE TABLE INSTRUCTIONS (
  RecipeID INT NOT NULL,
  Step_Number INT NOT NULL,
  Description VARCHAR(MAX) NOT NULL,
  CONSTRAINT INSTRUCTIONS_PK PRIMARY KEY (RecipeID, Step_Number),
  CONSTRAINT INS_REC_FK FOREIGN KEY (RecipeID)
    REFERENCES RECIPES(RecipeID)
    ON DELETE CASCADE ON UPDATE CASCADE
);
GO

CREATE TABLE INGREDIENTS (
  IngredientID INT NOT NULL IDENTITY(101,1) PRIMARY KEY,
  RecipeID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Quantity DECIMAL(8,2) NOT NULL,
  Unit VARCHAR(16) NULL,
  Special_Notes VARCHAR(MAX) NULL,
  CONSTRAINT ING_REC_FK FOREIGN KEY (RecipeID)
    REFERENCES RECIPES(RecipeID)
    ON DELETE CASCADE ON UPDATE CASCADE
);
GO

CREATE INDEX IX_INSTRUCTIONS_RecipeID ON INSTRUCTIONS(RecipeID);
CREATE INDEX IX_INGREDIENTS_RecipeID  ON INGREDIENTS(RecipeID);
GO
